Config.Reference = {}

-- :: Controls
Config.Reference.Controls = {
    -- https://docs.fivem.net/docs/game-references/controls/
    ByName = {
        ['INPUT_NEXT_CAMERA'] = 0, ['INPUT_LOOK_LR'] = 1, ['INPUT_LOOK_UD'] = 2, ['INPUT_LOOK_UP_ONLY'] = 3, ['INPUT_LOOK_DOWN_ONLY'] = 4, ['INPUT_LOOK_LEFT_ONLY'] = 5,
        -- too lazy to add all of them
    },
    QWERTY = {
        ['ESC'] = 202, ['F1'] = 288, ['F2'] = 289, ['F3'] = 170, ['F5'] = 166, ['F6'] = 167, ['F7'] = 168, ['F8'] = 169, ['F9'] = 56, ['F10'] = 57, ['F11'] = 344,
        ['`'] = 243, ['~'] = 243, ['1'] = 157, ['2'] = 158, ['3'] = 160, ['4'] = 164, ['5'] = 165, ['6'] = 159, ['7'] = 161, ['8'] = 162, ['9'] = 163, ['-'] = 84, ['_'] = 84, ['='] = 83, ['+'] = 83, ['BACKSPACE'] = 194,
        ['TAB'] = 37, ['Q'] = 85, ['W'] = 77, ['E'] = 38, ['R'] = 80, ['T'] = 245, ['Y'] = 246, ['U'] = 303, ['I'] = nil, ['O'] = nil, ['P'] = 199, ['['] = 312, ['{'] = 312, [']'] = 313, ['}'] = 312,
        ['CAPS'] = 217, ['CAPSLOCK'] = 217, ['A'] = 234, ['S'] = 78, ['D'] = 235, ['F'] = 49, ['G'] = 47, ['H'] = 304, ['J'] = nil, ['K'] = 311, ['L'] = 182, [';'] = nil, [':'] = nil, ["'"] = nil, ['"']= nil, ['ENTER'] = 191,
        ['LSHIFT'] = 209, ['Z'] = 48, ['X'] = 186, ['C'] = 26, ['V'] = 0, ['B'] = 305, ['N'] = 306, ['M'] = 301, [','] = nil, ['<'] = nil, ['.'] = nil, ['>'] = nil, ['/'] = nil, ['?'] = nil, ['RSHIFT'] = nil,
        ['LCTRL'] = 224, ['LALT'] = 19, ['SPACE'] = 179, ['SPACEBAR'] = 179, ['RALT'] = nil, ['FN'] = nil, ['RCTRL'] = nil, ['ARROW_UP'] = 172, ['ARROW_DOWN'] = 173, ['ARROW_LEFT'] = 174, ['ARROW_RIGHT'] = 175,
        ['INSERT'] = 121, ['INS'] = 121, ['HOME'] = 212, ['HM'] = 212, ['PAGE_UP'] = 316, ['PU'] = 316, ['PAGE_DOWN'] = 317, ['PD'] = 317, ['END'] = nil, ['DELETE'] = 296, ['DEL'] = 296
        -- too lazy to add all of them
    },
}
-- ::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::;


-- :: Others
Config.Reference.MapZone = {
    AIRP = { full = 'Los Santos International Airport', short = 'LSIA' },
    ALAMO = { full = 'Alamo Sea', short = 'Alamo Sea' },
    ALTA = { full = 'Alta', short = 'Alta' },
    ARMYB = { full = 'Fort Zancudo', short = 'Fort Zancudo' },
    BANHAMC = { full = 'Banham Canyon', short = 'Banham Canyon' },
    BANNING = { full = 'Banning', short = 'Banning' },
    BEACH = { full = 'Vespucci Beach', short = 'Vespucci Beach' },
    BHAMCA = { full = 'Banham Canyon', short = 'Banham Canyon' },
    BRADP = { full = 'Braddock Pass', short = 'Braddock Pass' },
    BRADT = { full = 'Braddock Tunnel', short = 'Braddock Tunnel' },
    BURTON = { full = 'Burton', short = 'Burton' },
    CALAFB = { full = 'Calafia Bridge', short = 'Calafia Bridge' },
    CANNY = { full = 'Raton Canyon', short = 'Raton Canyon' },
    CCREAK = { full = 'Cassidy Creek', short = 'Cassidy Creek' },
    CHAMH = { full = 'Chamberlain Hills', short = 'Chamberlain Hills' },
    CHIL = { full = 'Vinewood Hills', short = 'Vinewood Hills' },
    CHU = { full = 'Chumash', short = 'Chumash' },
    CMSW = { full = 'Chiliad Mountain State Wilderness', short = 'Chiliad Mountain' },
    CYPRE = { full = 'Cypress Flats', short = 'Cypress Flats' },
    DAVIS = { full = 'Davis', short = 'Davis' },
    DELBE = { full = 'Del Perro Beach', short = 'Del Perro Beach' },
    DELPE = { full = 'Del Perro', short = 'Del Perro' },
    DELSOL = { full = 'La Puerta', short = 'La Puerta' },
    DESRT = { full = 'Grand Senora Desert', short = 'Grand Senora Desert' },
    DOWNT = { full = 'Downtown', short = 'Downtown' },
    DTVINE = { full = 'Downtown Vinewood', short = 'Downtown Vinewood' },
    EAST_V = { full = 'East Vinewood', short = 'East Vinewood' },
    EBURO = { full = 'El Burro Heights', short = 'El Burro Heights' },
    ELGORL = { full = 'El Gordo Lighthouse', short = 'El Gordo Lighthouse' },
    ELYSIAN = { full = 'Elysian Island', short = 'Elysian Island' },
    GALFISH = { full = 'Galilee', short = 'Galilee' },
    GOLF = { full = 'GWC and Golfing Society', short = 'GWC and Golfing Society' },
    GRAPES = { full = 'Grapeseed', short = 'Grapeseed' },
    GREATC = { full = 'Great Chaparral', short = 'Great Chaparral' },
    HARMO = { full = 'Harmony', short = 'Harmony' },
    HAWICK = { full = 'Hawick', short = 'Hawick' },
    HORS = { full = 'Vinewood Racetrack', short = 'Vinewood Racetrack' },
    HUMLAB = { full = 'Humane Labs and Research', short = 'Humane Labs' },
    JAIL = { full = 'Bolingbroke Penitentiary', short = 'Bolingbroke Penitentiary' },
    KOREAT = { full = 'Little Seoul', short = 'Little Seoul' },
    LACT = { full = 'Land Act Reservoir', short = 'Land Act Reservoir' },
    LAGO = { full = 'Lago Zancudo', short = 'Lago Zancudo' },
    LDAM = { full = 'Land Act Dam', short = 'Land Act Dam' },
    LEGSQU = { full = 'Legion Square', short = 'Legion Square' },
    LMESA = { full = 'La Mesa', short = 'La Mesa' },
    LOSPUER = { full = 'La Puerta', short = 'La Puerta' },
    MIRR = { full = 'Mirror Park', short = 'Mirror Park' },
    MORN = { full = 'Morningwood', short = 'Morningwood' },
    MOVIE = { full = 'Richards Majestic', short = 'Richards Majestic' },
    MTCHIL = { full = 'Mount Chiliad', short = 'Mount Chiliad' },
    MTGORDO = { full = 'Mount Gordo', short = 'Mount Gordo' },
    MTJOSE = { full = 'Mount Josiah', short = 'Mount Josiah' },
    MURRI = { full = 'Murrieta Heights', short = 'Murrieta Heights' },
    NCHU = { full = 'North Chumash', short = 'North Chumash' },
    NOOSE = { full = 'N.O.O.S.E', short = 'N.O.O.S.E' },
    OCEANA = { full = 'Pacific Ocean', short = 'Pacific Ocean' },
    PALCOV = { full = 'Paleto Cove', short = 'Paleto Cove' },
    PALETO = { full = 'Paleto Bay', short = 'Paleto Bay' },
    PALFOR = { full = 'Paleto Forest', short = 'Paleto Forest' },
    PALHIGH = { full = 'Palomino Highlands', short = 'Palomino Highlands' },
    PALMPOW = { full = 'Palmer-Taylor Power Station', short = 'Palmer-Taylor Power Station' },
    PBLUFF = { full = 'Pacific Bluffs', short = 'Pacific Bluffs' },
    PBOX = { full = 'Pillbox Hill', short = 'Pillbox Hill' },
    PROCOB = { full = 'Procopio Beach', short = 'Procopio Beach' },
    RANCHO = { full = 'Rancho', short = 'Rancho' },
    RGLEN = { full = 'Richman Glen', short = 'Richman Glen' },
    RICHM = { full = 'Richman', short = 'Richman' },
    ROCKF = { full = 'Rockford Hills', short = 'Rockford Hills' },
    RTRAK = { full = 'Redwood Lights Track', short = 'Redwood Lights Track' },
    SANAND = { full = 'San Andreas', short = 'San Andreas' },
    SANCHIA = { full = 'San Chianski Mountain Range', short = 'San Chianski Mountain Range' },
    SANDY = { full = 'Sandy Shores', short = 'Sandy Shores' },
    SKID = { full = 'Mission Row', short = 'Mission Row' },
    SLAB = { full = 'Stab City', short = 'Stab City' },
    STAD = { full = 'Maze Bank Arena', short = 'Maze Bank Arena' },
    STRAW = { full = 'Strawberry', short = 'Strawberry' },
    TATAMO = { full = 'Tataviam Mountains', short = 'Tataviam Mountains' },
    TERMINA = { full = 'Terminal', short = 'Terminal' },
    TEXTI = { full = 'Textile City', short = 'Textile City' },
    TONGVAH = { full = 'Tongva Hills', short = 'Tongva Hills' },
    TONGVAV = { full = 'Tongva Valley', short = 'Tongva Valley' },
    VCANA = { full = 'Vespucci Canals', short = 'Vespucci Canals' },
    VESP = { full = 'Vespucci', short = 'Vespucci' },
    VINE = { full = 'Vinewood', short = 'Vinewood' },
    WINDF = { full = 'Ron Alternates Wind Farm', short = 'Ron Alternates Wind Farm' },
    WVINE = { full = 'West Vinewood', short = 'West Vinewood' },
    ZANCUDO = { full = 'Zancudo River', short = 'Zancudo River' },
    ZP_ORT = { full = 'Port of South Los Santos', short = 'Port of South Los Santos' },
    ZQ_UAR = { full = 'Davis Quartz', short = 'Davis Quartz' },
    PROL = { full = 'Puerto Del Sol', short = 'Puerto Del Sol' },
    ISHeist = { full = 'Cayo Perico Island', short = 'Cayo Perico Island' }
}
-- ::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::;